import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#E9E5FF',
  },
  header: {
    backgroundColor: '#7467FF',
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRight: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(59, 238, 115, 0.52)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRightPlaceholder: {
    width: 32,
  },
  screenTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
  },
  body: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  listContainer: {
    paddingBottom: 120,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  cardCompleted: {
    backgroundColor: '#EAE7FF',
  },
  cardText: {
    flex: 1,
    paddingRight: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#222',
    marginBottom: 6,
  },
  cardDetail: {
    fontSize: 14,
    color: '#6E6E7A',
  },
  completedText: {
    textDecorationLine: 'line-through',
    color: '#6E6E7A',
  },
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#F6F4FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  floatingButton: {
    position: 'absolute',
    right: 24,
    bottom: 26,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#5B4EFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5B4EFF',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 18,
    overflow: 'hidden',
    elevation: 3,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#5B4EFF',
  },
  tabText: {
    fontSize: 14,
    color: '#6E6E7A',
    fontWeight: '600',
  },
  tabTextActive: {
    color: '#fff',
  },
  noTasksText: {
    marginTop: 24,
    textAlign: 'center',
    color: '#6E6E7A',
    fontSize: 16,
  },
  formGroup: {
    marginBottom: 18,
  },
  label: {
    color: '#4A4A4A',
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#222',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  button: {
    marginTop: 10,
    backgroundColor: '#5B4EFF',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  updateButton: {
    flex: 1,
    marginRight: 8,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#9A92FF',
    marginLeft: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  editActions: {
    flexDirection: 'row',
    marginTop: 10,
  },
});
